export * from "../api/client";
export { authApi } from "../api/auth";
export { projectsApi } from "../api/projects";
export { tasksApi } from "../api/tasks";
export { financeApi } from "../api/finance";
export { mpesaApi } from "../api/mpesa";
export { inventoryApi } from "../api/inventory";
export { scrapersApi } from "../api/scrapers";
export { hrApi } from "../api/hr";
export { techniciansApi } from "../api/technicians";
export { crmApi } from "../api/crm";
export { workflowApi } from "../api/workflow";
export { dashboardsApi } from "../api/dashboards";
export { usersApi, permissionsApi } from "../api/system";
export { auditApi } from "../api/audit";
export { rbacApi, managementApi } from "../api/rbac";
